### ISSUE TITLE
improve (fix) tnefparse logging

### ISSUE THREAD

**Issue by petri** [koodaamo/tnefparse#18]
Currently, logging in tnefparse is a bit of a mess and should be improved.

This issue is to gather input for that. If you don't like how tnefparse logs warnings etc. please submit a proposal under this issue.

**Comment by jrideout** [comment]
In general the logging isn't so bad. The problem are the things like `WARNING  Unknown TNEF Object: <TNEFObject 'Message ID'>` that clutter things up and I think causes confusion (since this doesn't mean there is something wrong).

What we probably need to do is set all attributes we observe dynamically, not just the mapi attributes.

**Comment by petri** [comment]
I removed some of those more or less unnecessary warnings. Let's close this, we can reopen if needed.
